### ISSUE TITLE
Frontend to-do list

### ISSUE THREAD

**Issue by PeiShang** [AlphaTac-AI/AlphaTac-Frontend#9]
### Home page
- [ ] AlphaTacAI Home Page
### DoTA2 Page
- [ ] receive data from backend, and render upcoming matches as a list.

- [ ] update content automatically while new data are available

- [ ] add logos for teams and beautify the page.
### about page
- [ ] page about the team and project

**Comment by PeiShang** [comment]
### main page
![image](https://user-images.githubusercontent.com/37992256/40275895-41df9452-5c2f-11e8-9c4b-574e8df9128b.png)
### about page
![image](https://user-images.githubusercontent.com/37992256/40275898-4f850d26-5c2f-11e8-95e2-8208b4e0621b.png)
### team page
![image](https://user-images.githubusercontent.com/37992256/40275899-5df4263a-5c2f-11e8-95d7-b7af436b3a4a.png)
### product page1
![image](https://user-images.githubusercontent.com/37992256/40275903-6b607300-5c2f-11e8-97e7-961767f0185d.png)
### product page2(optinal)
![image](https://user-images.githubusercontent.com/37992256/40275906-7ac2f76e-5c2f-11e8-8d13-530537ffc8ff.png)
